### ISSUE TITLE
Does it work in local testing?

### ISSUE THREAD

**Issue by omgitsraven** [hfcRed/Player-Tracker#12]
I haven't been able to try this with other real users yet, but when I try with a second copy of myself in a Build & Test instance, nothing happens when I make the fist gesture....   Have I set something up wrong, or does it not work properly in that kind of testing scenario?

**Comment by hfcRed** [comment]
This system is a bit outdated at the moment, you should use this one instead:
https://github.com/VRLabs/Contact-Tracker
