### ISSUE TITLE
Integrated example

### ISSUE THREAD

**Issue by omgitsraven** [hfcRed/Player-Tracker#13]
Have you thought about providing a unitypackage of the player tracker already integrated on a simple example avatar (even just the default robot), just to reference as an example of what the setup should look like?

I'm having some trouble getting the tracker working on my avatar, and I'm not sure what step I misunderstood; it would be handy for me to have a finished example of how it's meant to be, to cross-reference.

**Comment by hfcRed** [comment]
As with the other issue, please use the VRLabs tracker instead, as this package is outdated:
https://github.com/VRLabs/Contact-Tracker
